---
title: "CART Lab I (L03)"
author: "Data Science III (STAT 301-3)"
date: "April 9th, 2018"
output: html_document
---

# Overview

There are two goals for this lab. The first is to continue practicing both the implementation of a consistent and organized style-guide and implementation of `tidyverse` coding enhancements to the base R code provided in the book. The second is to practice the application of tree-based methods (i.e., classification and regression trees).

# Datasets 

We will be utilizing the `Carseats` (*carseats.csv*) and `Boston` (*boston.csv*) datasets contained in the **data** subdirectory. While these datasets are included within R packages, students are expected to read in these datasets utilizing `tidyverse` technique. This may necessitate that students re-type variables. Students can access the appropriate codebook by using `?ISLR::Carseats` or `?MASS::Boston`.

# Exercise

Please complete the following exercise.The document should be neatly formatted. 

#### Load Packages

```{r, message=FALSE}
# Loading package(s)

```
<br>

#### Exercise 1
Work through the entire lab in Section 8.3 *Lab: Decision Trees* (pages: 323 - 331) while attempting to utilize `tidyverse` techniques when possible. 

Please note that *"attempting to utilize `tidyvere` techniques when possible"* entails that students make an **honest** effort to implement these techniques. Copying, pasting, running, and submitting the code provided in the book does not constitute an **honest** effort. 

<<<<<<< HEAD
While it might feel redundant to re-create code in a slightly different format, it is an extremely useful skill to practice. It is only really redundant because base R code is supplied. The base R code provides a good starting point for us to build upon and improve it by coverting it to a more flexible and organized format. Students should also consider adding their own notes and commentary to make this lab into a useful resource for the future. 

<br><br>
=======
While it might feel redundant to re-create code in a slightly different format, it is an extremely useful skill to practice. It is only really redundant because base R code is supplied. The base R code provides a good starting point for us to build upon and improve it by coverting it to a more flexible and organized format. Students should also consider adding their own notes and commentary to make this lab into a useful resource for the future. 
>>>>>>> a9cd655ac41b6abd18fc696d8b6fc4fe83e1508e
